---
title: "Publications"
---

### 2025
Pang, Z., Fu, Y., Lala, D., **Elmers, M.**, Inoue, K., Kawahara, T. 2025. Human-Like Embodied AI Interviewer: Employing Android ERICA in Real International Conference. *Proc. 31st International Conference on Computational Linguistics: System Demonstrations (COLING '25)*, Abu Dhabi, Jan 19-24.
[Link](https://aclanthology.org/2025.coling-demos.14/)

### 2024
Lala, D., Inoue, K., Kawai, H., Pang, Z., **Elmers, M.**, Kawahara, T. 2024. Development and evaluation of a semi-autonomous parallel attentive listening system. *Proc. 2024 Asia Pacific Signal and Information Processing Association Annual Summit and Conference (APSIPA ASC)*, Macau, Dec 3-6. [PDF](https://ieeexplore.ieee.org/document/10848649) [.bib](publications/lala2024apsipa.bib)

**Elmers, M.**, Inoue, K., Lala, D., Ochi, K., and Kawahara, T. 2024. Analysis and Detection of Differences in Spoken User Behaviors between Autonomous and Wizard-of-Oz Systems. *Proc. 27th Conference of the Oriental COCOSDA (O-COCOSDA '24)*, Hsinchu, Oct 17-19. [PDF](https://ieeexplore.ieee.org/document/10799979) [.bib](publications/elmers_ococosda24.bib) [Poster](publications/elmers_ococosda24_poster.pdf) [Code](https://github.com/MikeyElmers/paper_ococosda24)

### 2023
**Elmers, M.**. 2023. Evaluating pause particles and their functions in natural and synthesized speech in laboratory and lecture settings. PhD thesis, Saarland University. [PDF](publications/elmers_dissertation.pdf) [.bib](publications/elmers_dissertation.bib) [DOI](http://dx.doi.org/10.22028/D291-41118)    
<br>
**Elmers, M.** and Székely, É. 2023. The impact of pause-internal phonetic particles on recall in synthesized lectures. *Proc. 12th ISCA Speech Synthesis Workshop (SSW '23)*, Grenoble, Aug 26-28, pp. 204-210. [PDF](publications/elmers_ssw23_paper.pdf) [.bib](publications/elmers_ssw23.bib) [Poster](publications/elmers_ssw23_poster.pdf) [Code](https://github.com/MikeyElmers/paper_ssw23) [Demo](https://mikeyelmers.github.io/paper_ssw23ttsdemo/)  
<br>
**Elmers, M.**, O'Mahony, J., and Székely, É. 2023. Synthesis after a couple PINTs: Investigating the role of pause-internal phonetic particles in speech synthesis and perception. *Proc. Interspeech 2023*, Dublin, Aug 20-24, pp. 4843-4847. [PDF](publications/elmers_interspeech23_paper.pdf) [.bib](publications/elmers_interspeech23.bib) [Poster](publications/elmers_interspeech23_poster.pdf) [Code](https://github.com/MikeyElmers/paper_interspeech23) [Demo](https://mikeyelmers.github.io/paper_interspeech23ttsdemo/)  
<br>
**Elmers, M.** 2023. Pause particles influencing recollection in lectures. *Proc. 20th International Congress of Phonetic Sciences (ICPhS '23)*, Prague, August 7-11, pp. 37-41. [PDF](publications/elmers_icphs23_paper.pdf) [.bib](publications/elmers_icphs23.bib) [Poster](publications/elmers_icphs23_poster.pdf) [Code](https://github.com/MikeyElmers/paper_icphs23)

### 2022
**Elmers, M.** and Trouvain, J. 2022. Pause-internal particles in university lectures. Poster presentation, *18th Phonetik & Phonologie (P&P '22)*, Bielefeld, October 06-07. [Abstract](publications/elmers_pp22_abstract.pdf) [Poster](publications/elmers_pp22_poster.pdf) [Code](https://github.com/MikeyElmers/paper_pp22)
<br>

**Elmers, M.** 2022. Comparing detection methods for pause-internal particles. *Proc. 33rd Conference Elektronische Sprachsignalverarbeitung (ESSV '22)*, Sonderborg, March 2-4, pp. 204-211. [PDF](publications/elmers_essv2022.pdf) [.bib](publications/elmers_essv2022.bib) [Slides](publications/elmers_essv2022presentation.pdf)

### 2021
**Elmers, M.** 2021. Corpus generation for research in pause-internal phonetic particles. Oral presentation, *17th Phonetik & Phonologie (P&P '21)*, Frankfurt, September 29-30. [Abstract](publications/elmers_P&P21_Abstract.pdf) [Slides](publications/elmers_P&P21_Slides.pdf)  
<br>
Muhlack, B., **Elmers, M.**, Drenhaus, H., Trouvain, J., Van Os, M., Werner, R., Ryzhova, M., and Möbius, B. 2021. Revisiting recall effects of filler particles in German and English. *Proc. Interspeech 2021*, Aug 30 - Sept 03, pp. 3979-3983. [PDF](publications/Muhlack_Interspeech21.pdf) [.bib](publications/Muhlack_Interspeech21.bib) [Stimuli](https://cloud.hiz-saarland.de/s/N4RZamosiXXiL4s)  
<br>
**Elmers, M.**, Werner, R., Muhlack, B., Möbius, B., and Trouvain, J. 2021. Take a breath: Respiratory sounds improve recollection in synthetic speech. *Proc. Interspeech 2021*, Brno, Aug 30 - Sept 03, 3196-3200. [PDF](publications/elmers_Interspeech21.pdf) [.bib](publications/elmers_Interspeech21.bib) [Stimuli](https://cloud.hiz-saarland.de/s/TLGsZ2EfyBHqHpi)  
<br>
**Elmers, M.**, Werner, R., Muhlack, B., Möbius, B., and Trouvain, J. 2021. Evaluating the effect of pauses on number recollection in synthesized speech. *Proc. 32nd Conference Elektronische Sprachsignalverarbeitung (ESSV '21)*, Berlin, March 3-5, pp. 289-295. [PDF](publications/elmers_ESSV2021_Paper.pdf) [.bib](publications/elmers_ESSV2021.bib) [Slides](publications/elmers_ESSV2021_Presentation.pdf)  

### 2020
**Elmers, M.**, Muhlack, B., Werner, R., Trouvain, J., and Möbius, B. 2020. Pause-internal phonetic particles in speech communication. Poster presentation, *16th Phonetik & Phonologie (P&P '20)*, Trier, September 10-11. [Abstract](publications/PINTS_Abstract.pdf) [Poster](publications/PINTS_Poster.pdf)